name: Python CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff - lint
        run: ruff check --no-fix .

      - name: Ruff - format check
        run: ruff format --check .

      - name: Mypy - type check
        run: mypy .
